import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/srs-profile-pic-3.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2 '
            >
              <Image src={profilePic} alt='Saidur Rahmans Portfolio' className='w-[70%] h-auto' />
            </div>
            <div className='w-[50%] flex flex-col items-center self-center'>

              <AnimatedText text="Fusing Imagination, Coding, and Design to Manifest Dreams into Digital Reality." className='!text-6xl !text-left'>

              </AnimatedText>
              <p className='my-4 text-base font-medium'>As a professional full-stack developer, data science enthusiast, and AI collaborator, I am committed to developing ideas into creative online apps. Furthermore, I am actively involved in developing cutting-edge models to investigate the domains of artificial intelligence. Explore my most recent projects and writings, which demonstrate my experience in React.js, web development, and the amazing area of data science and AI.</p>

              <div className='flex items-center self-start mt-2'>
                <Link href="./dummy.pdf" target='_blank'
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1 "}></LinkArrow>
                </Link>

                <Link href="mailto:sr.sujon.cyb@gmail.com" target='_blank'
                  className='flex items-center ml-4 text-lg font-medium capitalize bg-light text-dark px-6 rounded-lg underline border-2 border-solid border-transparent hover:border-dark '
                >Contact</Link>
              </div>

            </div>

          </div>
        </Layout>
      </main>
    </>
  )
}
